FULL_NAMES = [
    "Budi Santoso",
    "Siti Nurhaliza",
    "Andi Wijaya",
    "Dewi Kusuma Wardhani",
    "Rizki Ramadhan",
    "Putri Ayu Lestari",
    "Ahmad Fauzi",
    "Maya Sari Indah",
    "Dedi Kurniawan",
    "Fitri Handayani",
    "Agus Prasetyo",
    "Ratna Sari",
    "Hendra Gunawan",
    "Lina Marlina",
    "Bambang Suryanto",
    "Indah Permata Sari",
    "Wahyu Hidayat",
    "Rina Susanti",
    "Eko Prabowo",
    "Yuni Astuti",
    "Rudi Hartono",
    "Sri Wahyuni",
    "Dimas Pratama",
    "Nur Azizah",
    "Fajar Nugroho",
    "Tari Wulandari",
    "Irwan Setiawan",
    "Mega Puspita",
    "Joko Widodo",
    "Ani Yudhoyono",
    "Surya Dharma",
    "Lia Amalia",
    "Hadi Kusuma",
    "Wati Rahayu",
    "Arief Rahman",
    "Sinta Dewi",
    "Tono Sugiarto",
    "Nita Anggraini",
    "Bayu Nugraha",
    "Erni Sulastri",
    "Doni Saputra",
    "Ika Wijayanti",
    "Rian Firmansyah",
    "Diah Ayu Ningrum",
    "Harjo Wibowo",
    "Endang Lestari",
    "Gunawan Pranoto",
    "Yanti Kurniasih",
    "Teguh Santoso",
    "Dwi Handayani",
    "Amin Abdullah",
    "Sari Mulyani",
    "Benny Setiawan",
    "Ratih Puspasari",
    "Heru Sucipto",
    "Vina Handayani",
    "Arif Budiman",
    "Linda Suryani",
    "Dedy Hermawan",
    "Yuliana Sari",
    "Roni Kurniawan",
    "Diana Permatasari",
    "Wawan Setiadi",
    "Erni Ratnawati",
    "Agung Pramono",
    "Nia Rahmawati",
    "Iwan Gunawan",
    "Tuti Handayani",
    "Sigit Purnomo",
    "Evi Susanti",
    "Cahyo Wibowo",
    "Ayu Lestari",
    "Yanto Wijaya",
    "Suci Rahayu",
    "Hendro Purnomo",
    "Dewi Anggraini",
    "Reza Pahlevi",
    "Wulan Sari",
    "Adi Nugroho",
    "Rina Kartika",
    "Bima Sakti",
    "Lilis Suryani",
    "Hari Susanto",
    "Nining Maryati",
    "Farid Kurniawan",
    "Melati Kusuma",
    "Andri Saputra",
    "Yati Wahyuni",
    "Rudy Setiawan",
    "Tri Utami",
    "Anwar Hidayat",
    "Siska Wulandari",
    "Hendra Gunawan",
    "Lia Kartini",
    "Didik Prasetyo",
    "Mira Susanti",
    "Raden Ahmad",
    "Siti Fatimah",
    "Bambang Hartono",
    "Ningsih Rahayu",
    "Doni Kusuma",
    "Fitria Handayani",
    "Yudi Pranata",
    "Sri Lestari",
    "Anto Wijaya",
    "Dewi Sartika",
    "Usman Abdullah",
    "Ratna Dewi",
    "Edi Susilo",
    "Maya Puspita",
    "Taufik Hidayat",
    "Rini Wulandari",
    "Lukman Hakim",
    "Anis Rahmawati",
    "Gilang Ramadhan",
    "Intan Permata",
    "Zaenal Arifin",
    "Yulia Kartika",
    "Firman Syahputra",
    "Ika Susanti",
    "Ridwan Kamil",
    "Laila Sari",
    "Basuki Rahmat",
    "Wiwik Susilowati",
    "Deden Supriyadi",
    "Citra Dewi",
    "Aan Mansyur",
    "Ratih Kusuma",
    "Imam Santoso",
    "Nurul Hidayah",
    "Aris Munandar",
    "Yessi Gusman",
    "Dede Yusuf",
    "Lina Herlina",
    "Faisal Rahman",
    "Retno Wulan",
    "Yoga Aditya",
    "Widya Ningrum",
    "Purnomo Hadi",
    "Sulis Setiawati",
    "Irfan Hakim",
    "Erna Susanti",
    "Catur Nugroho",
    "Dini Puspita",
    "Ridho Pratama",
    "Santi Wulansari",
    "Haryanto Wijaya",
    "Umi Kalsum",
    "Sofyan Basir",
    "Novi Andriani",
    "Zainal Mutaqin",
    "Dwi Ratnasari",
    "Kurnia Sandi",
    "Aisyah Putri",
    "Rahman Hakim",
    "Elsa Purnama",
    "Jefri Nichol",
    "Rosa Meldianti",
    "Arman Maulana",
    "Siska Meliana",
    "Dedy Mizwar",
    "Ria Irawan",
    "Tanto Hartono",
    "Yenni Wahid",
    "Bram Dermawan",
    "Vicky Shu",
    "Rama Wijaya",
    "Ayu Tingting",
    "Fadli Zon",
    "Nunung Srimulat",
    "Arifin Panigoro",
    "Krisdayanti",
    "Prabowo Subianto",
    "Sandiaga Uno",
    "Anies Baswedan",
    "Ganjar Pranowo",
    "Ridwan Kamil",
    "Tri Rismaharini",
    "Khofifah Indar",
    "Djarot Saiful",
    "Ahok Basuki",
    "Fauzi Bowo",
    "Sutiyoso",
    "Ali Sadikin",
    "Hendrawan Supratikno",
    "Mahfud MD",
    "Yusril Ihza",
    "Adnan Buyung",
    "Hotman Paris",
    "Otto Hasibuan",
    "Todung Mulya",
    "Ruhut Sitompul",
    "Said Iqbal",
    "Andi Arief",
    "Roy Suryo",
    "Fadli Zon",
    "Fahri Hamzah",
    "Budiman Sudjatmiko",
    "Dian Sastro",
    "Titi Kamal",
    "Chelsea Islan",
    "Raisa Andriana",
    "Isyana Sarasvati",
    "Andien Aisyah",
    "Maudy Ayunda",
    "Bunga Citra",
    "Afgan Syahreza",
    "Glenn Fredly",
    "Judika Sihotang",
    "Rossa Roslaina",
    "Agnes Monica",
    "Anggun Cipta",
    "Rio Dewanto",
    "Nicholas Saputra",
    "Iko Uwais",
    "Joe Taslim",
    "Yayan Ruhian",
    "Cecep Arif",
    "Tara Basro",
    "Laura Basuki",
    "Reza Rahadian",
    "Marsha Timothy",
    "Ringgo Agus",
    "Nirina Zubir",
    "Surya Saputra",
    "Cynthia Lamusu",
    "Indra Brugman",
    "Aura Kasih",
    "Luna Maya",
    "Cut Tari",
    "Dian Pelangi",
    "Ivan Gunawan",
    "Denny Cagur",
    "Andre Taulany",
    "Raffi Ahmad",
    "Nagita Slavina",
    "Ayu Ting",
    "Ruben Onsu",
    "Sarwendah Tan",
    "Ashanty Hermansyah",
    "Anang Hermansyah",
    "Aurel Hermansyah",
    "Azriel Hermansyah",
    "Arsy Hermansyah",
    "Syahrini Reino",
    "Inul Daratista",
    "Dewi Perssik",
    "Zaskia Gotik",
    "Lucinta Luna",
    "Barbie Kumalasari",
    "Saipul Jamil",
    "Soimah Pancawati",
    "Ayu Azhari",
    "Sarah Azhari",
    "Rahma Azhari",
    "Ibra Azhari",
    "Dwi Andhika",
    "Ussy Sulistiawaty",
    "Andhika Pratama",
    "Ussy Sulistiawaty",
    "Melaney Ricardo",
    "Tyson Lynch",
    "Maia Estianty",
    "Irwan Mussry",
    "Ahmad Dhani",
    "Mulan Jameela",
    "Al Ghazali",
    "Dul Jaelani",
    "Tiara Savitri",
    "Nafa Urbach",
    "Zack Lee",
    "Natasha Rizky",
    "Desta Mahendra",
    "Vincent Rompies",
    "Hesti Purwadinata",
    "Desta Vincent",
    "Parto Patrio",
    "Rina Nose",
    "Aziz Gagap",
    "Wendy Cagur",
    "Ruben Onsu",
    "Jordi Onsu",
    "Ayu Dewi",
    "Regi Datau",
    "Tasya Kamila",
    "Randi Bachtiar",
    "Irish Bella",
    "Ammar Zoni",
    "Syahnaz Sadiqah",
    "Jeje Govinda",
    "Gading Marten",
    "Gisel Anastasia",
    "Gempi Gisel",
    "Wijin Novianto",
    "Wulan Guritno",
    "Adilla Dimitri",
    "Pasha Ungu",
    "Okie Agustina",
    "Gunawan Dwi",
    "Wendi Cagur",
    "Sule Sutisna",
    "Nathalie Holscher",
    "Lina Zubaedah",
    "Rizky Febian",
    "Putri Delina",
    "Ferdy Sambo",
    "Putri Candrawathi",
    "Richard Eliezer",
    "Bharada E",
    "Ferdian Paleka",
    "Ria Ricis",
    "Teuku Ryan",
    "Oki Setiana",
    "Shindy Putri",
    "Zaskia Sungkar",
    "Irwansyah",
    "Shireen Sungkar",
    "Teuku Wisnu",
    "Laudya Bella",
    "Engku Emran",
    "Zaskia Adya",
    "Hanung Bramantyo",
    "Arumi Bachsin",
    "Emil Dardak",
    "Nikita Willy",
    "Indra Priawan",
    "Rachel Vennya",
    "Niko Al",
    "Salim Nauderer",
    "Okin Putra",
    "Indah Permatasari",
    "Arie Kriting",
    "Indah Permatasari",
    "Vidi Aldiano",
    "Sheila Dara",
    "Sherina Munaf",
    "Baskara Mahendra",
    "Tulus Rusyanto",
    "Pamungkas Aditya",
    "Fiersa Besari",
    "Nadin Amizah",
    "Sal Priadi",
    "Maliq Ibrahim",
    "Angga Puradiredja",
    "Baim Wong",
    "Paula Verhoeven",
    "Zaskia Gotik",
    "Sirajuddin Mahmud",
    "Alyssa Daguise",
    "Al Ghazali",
    "Laura Theux",
    "Margin Wieheerm",
    "Ali Syakieb",
    "Nadya Mustika",
    "Rizki DA",
    "Lesti Kejora",
    "Rizky Billar",
    "Happy Asmara",
    "Denny Caknan",
    "Yeni Inka",
    "Adella Safitri",
    "Gus Azmi",
    "Chacha Sherly",
    "Fadhlan Syah",
    "Yollanda Aditya",
    "Tasya Rosmala",
    "Deviana Safara",
    "Eny Sagita",
    "Yeyen Vivia",
    "Vita Alvia",
    "Fira Azahra",
    "Sarah Brillian",
    "Wandra Restusiyan",
    "Ilux ID",
    "Mahesa Ofki",
    "Didi Kempot",
    "Yan Vellia",
    "Ndarboy Genk",
    "Kiki Anggun",
    "Arlida Putri",
    "Syahiba Saufa",
    "Putri Kristya",
    "Luluk Darara",
    "Anisa Rahma",
    "Clara Gopa",
    "Jihan Audy",
    "Shinta Gisul",
    "Ayunda Diana",
    "Wahyu Selow",
    "Didik Budi",
    "Cak Percil",
    "Yudha Karengge",
    "Mbah Mijan",
    "Ki Joko",
    "Mama Dedeh",
    "Habib Rizieq",
    "Ustad Somad",
    "Ustad Khalid",
    "Ustadzah Oki",
    "Zainuddin MZ",
    "Aa Gym",
    "Arifin Ilham",
    "Mamah Dedeh",
    "Buya Yahya",
    "Habib Syech",
    "Gus Miftah",
    "Cak Nun",
    "Emha Ainun",
    "Butet Kertaradjasa",
    "Sujiwo Tejo",
    "Sapardi Djoko",
    "Chairil Anwar",
    "Pramoedya Toer",
    "Andrea Hirata",
    "Tere Liye",
    "Dee Lestari",
    "Raditya Dika",
    "Ernest Prakasa",
    "Pandji Pragiwaksono",
    "Raditya Oloan",
    "Arief Muhammad",
    "Jerome Polin",
    "Ria Ricis",
    "Atta Halilintar",
    "Aurel Hermansyah",
    "Ashanty Hermansyah",
    "Krisdayanti",
    "Mulan Jameela",
    "Maia Estianty",
    "Yuni Shara",
    "Titi DJ",
    "Ruth Sahanaya",
    "Harvey Malaiholo",
    "Fariz RM",
    "Vina Panduwinata",
    "Chrisye Purwana",
    "Iwan Fals",
    "Ebiet G Ade",
    "Gombloh",
    "Bimbo Group",
    "Koes Plus",
    "Panbers",
    "God Bless",
    "Slank",
    "Dewa 19",
    "Sheila On 7",
    "Peterpan",
    "Noah Band",
    "Ungu Band",
    "Gigi Band",
    "Padi Reborn",
    "Nidji",
    "J-Rocks",
    "Radja",
    "Samson",
    "D Masiv",
    "Letto",
    "Seventeen",
    "Kahitna",
    "Cokelat",
    "Ada Band",
    "Wali Band",
    "Armada Band",
    "Papinka",
    "Repvblik",
    "Hijau Daun",
    "Five Minutes",
    "Kerispatih",
    "Merpati Band",
    "Kangen Band",
    "ST12",
    "Zivilia",
    "Lyla",
    "Sigma",
    "Dadali",
    "Yovie Nuno",
    "Rizky Nazar",
    "Hanggini",
    "Jeff Smith",
    "Anya Geraldine",
    "Jessica Mila",
    "Verrell Bramasta",
    "Wilona Natasha",
    "Stefan William",
    "Celine Evangelista",
    "Kevin Aprilio",
    "Vicy Melanie",
    "Billy Syahputra",
    "Amanda Manopo",
    "Herjunot Ali",
    "Prisia Nasution",
    "Raihaanun",
    "Adipati Dolken",
    "Randy Pangalila",
    "Mikha Tambayong",
    "Deva Mahenra",
    "Aurelie Moeremans",
    "Mike Lewis",
    "Randy Martin",
    "Maria Vania",
    "Putri Marino",
    "Chicco Jerikho",
    "Julie Estelle",
    "Hannah Al Rashid",
    "Ariel Tatum",
    "Maxime Bouttier",
    "Morgan Oey",
    "Enzy Storia",
    "Randy Danistha",
    "Mawar De Jongh",
    "Bryan Domani",
    "Megan Domani",
]

GENDERS = ["male", "female"]

MARITAL_STATUSES = ["single", "married", "divorced", "widowed"]

EMPLOYMENT_TYPES = [
    "civil_servant",
    "private_employee",
    "state_owned_employee",
    "contract_employee",
    "freelancer",
    "entrepreneur",
    "business_owner",
    "farmer",
    "fisherman",
    "laborer",
    "teacher",
    "lecturer",
    "health_worker",
    "student",
    "homemaker",
    "retired",
    "unemployed",
]

RELATIONSHIPS = [
    "father",
    "mother",
    "husband",
    "wife",
    "child",
    "sibling",
    "grandfather",
    "grandmother",
    "uncle",
    "aunt",
    "cousin",
    "guardian",
    "other",
]

CITIES = ["Jakarta", "Blitar", "Wonogiri", "Malang"]
